<?php
/**
 * Created by PhpStorm.
 * User: xiangang
 * Date: 2017/9/20
 * Time: 上午10:38
 */

namespace DesignPattern\Visitor;


class CompositeArmy extends Unit
{
    protected $units = [];

    protected $salary = 0;


    /**
     * @param ArmyVisitor $visitor
     */
    public function accept(ArmyVisitor $visitor)
    {
        parent::accept($visitor); // TODO: Change the autogenerated stub
        foreach ($this->units as $unit) {
            $unit->accept($visitor);
        }
    }

    /**
     * @param Unit $unit
     */
    public function addUnit(Unit $unit)
    {
        if (in_array($unit,$this->units,true)) {
            return;
        }
        $this->salary += $unit->getSalary();
        $this->units[] = $unit;
    }

    /**
     * @param Unit $unit
     */
    public function removeUnit(Unit $unit)
    {
        $this->units = array_udiff($this->units, array($unit), function ($a, $b) {
            return ($a === $b ? 0 : 1);
        });
    }

}